# Generated by Django 4.0.4 on 2023-07-18 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audio', '0004_alter_sessiontranscript_transcript_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontranscript',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
