# Generated by Django 4.0.4 on 2023-07-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0005_alter_sessiontranscript_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontranscript',
            name='session_title',
            field=models.CharField(default='Untitled Session', max_length=255, null=True),
        ),
    ]
