# Generated by Django 4.0.4 on 2023-07-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0006_sessiontranscript_session_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontranscript',
            name='session_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
